# Generated by Django 4.2.30 on 2026-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="method",
            field=models.CharField(
                choices=[
                    ("face_recognition", "Face Recognition"),
                    ("qr_scan", "QR Scan"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
