# Generated by Django 4.2.30 on 2026-10-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0010_facesample"),
        ("scheduler", "0012_subject_required_tas_and_more"),
        ("attendance", "0003_attendance_method_qr_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence/distance score if marked via face recognition",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who manually marked or overrode this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="accounts.faculty",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="scheduler.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendance.attendancesession",
            ),
        ),
    ]
