# Generated by Django 4.2.30 on 2026-10-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_student_cgpa_semesters_student_marks_10th_and_more"),
        ("scheduler", "0012_subject_required_tas_and_more"),
        ("attendance", "0005_make_session_faculty_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="accounts.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="scheduler.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_alert_logs",
                "ordering": ["-dispatched_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "subject"],
                        name="attendance__student_e8ec84_idx",
                    )
                ],
            },
        ),
    ]
