import { useState, useEffect } from 'react';
import api from '../../api/axios';
import { useAuth } from '../../context/AuthContext';
import './TimetablePage.css';

export default function TimetablePage() {
  const [timetable, setTimetable] = useState([]);
  const [loading, setLoading] = useState(true);
  const { isAdmin } = useAuth();

  const days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
  const dayLabels = {
    MON: 'Monday', TUE: 'Tuesday', WED: 'Wednesday',
    THU: 'Thursday', FRI: 'Friday', SAT: 'Saturday',
  };

  const timeSlots = [
    '09:00', '10:00', '11:00', '13:00', '14:00', '15:00',
  ];

  useEffect(() => {
    loadTimetable();
  }, []);

  const loadTimetable = async () => {
    setLoading(true);
    try {
      const response = await api.get('/api/scheduler/timetable/');
      setTimetable(response.data.results || response.data || []);
    } catch (err) {
      console.error('Failed to load timetable:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    if (!confirm('This will replace the existing timetable. Continue?')) return;

    try {
      const response = await api.post('/api/scheduler/generate/');
      alert(response.data.message);
      loadTimetable();
    } catch (err) {
      alert(err.response?.data?.error || 'Failed to generate timetable.');
    }
  };

  const getClassForSlot = (day, time) => {
    return timetable.find(
      entry => entry.day === day && entry.start_time?.substring(0, 5) === time
    );
  };

  // Color palette for subjects
  const subjectColors = {};
  const colorPalette = [
    'var(--gradient-primary)',
    'var(--gradient-emerald)',
    'var(--gradient-sunset)',
    'var(--gradient-pink)',
    'linear-gradient(135deg, #06b6d4, #0891b2)',
    'linear-gradient(135deg, #a855f7, #9333ea)',
  ];

  const getSubjectColor = (subjectCode) => {
    if (!subjectColors[subjectCode]) {
      const idx = Object.keys(subjectColors).length % colorPalette.length;
      subjectColors[subjectCode] = colorPalette[idx];
    }
    return subjectColors[subjectCode];
  };

  if (loading) {
    return (
      <div className="page-container">
        <div className="loading-spinner"><div className="spinner" /></div>
      </div>
    );
  }

  return (
    <div className="page-container">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1>Class Timetable</h1>
          <p>Weekly schedule generated by the constraint satisfaction algorithm</p>
        </div>
        {isAdmin && (
          <button
            className="btn btn-primary"
            onClick={handleGenerate}
            id="btn-generate-timetable"
          >
            ⚡ Generate New
          </button>
        )}
      </div>

      {timetable.length === 0 ? (
        <div className="glass-card" style={{ padding: '3rem' }}>
          <div className="empty-state">
            <div className="empty-icon">📅</div>
            <h3>No Timetable Generated</h3>
            <p>
              {isAdmin
                ? 'Click "Generate New" to create a conflict-free timetable using the CSP solver.'
                : 'The admin has not generated a timetable yet.'}
            </p>
          </div>
        </div>
      ) : (
        <div className="glass-card timetable-wrapper animate-fade-in-up" style={{ opacity: 0 }}>
          <div className="timetable-grid">
            {/* Header row */}
            <div className="timetable-header">Time</div>
            {days.map(day => (
              <div className="timetable-header" key={day}>
                {dayLabels[day]}
              </div>
            ))}

            {/* Time slot rows */}
            {timeSlots.map(time => (
              <>
                <div className="timetable-time" key={`time-${time}`}>
                  {time}
                </div>
                {days.map(day => {
                  const cls = getClassForSlot(day, time);
                  return (
                    <div className="timetable-cell" key={`${day}-${time}`}>
                      {cls && (
                        <div
                          className="class-card"
                          style={{ background: getSubjectColor(cls.subject_code) }}
                        >
                          <div className="class-name">{cls.subject_code}</div>
                          <div className="class-room">📍 {cls.room_number}</div>
                          <div className="class-room">{cls.faculty_name}</div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </>
            ))}
          </div>
        </div>
      )}

      {/* Legend */}
      {timetable.length > 0 && (
        <div className="glass-card timetable-legend animate-fade-in-up stagger-3" style={{ opacity: 0, marginTop: '1.5rem', padding: '1.5rem' }}>
          <h3 className="section-title" style={{ marginBottom: '1rem' }}>Subjects</h3>
          <div className="legend-items">
            {[...new Set(timetable.map(t => t.subject_code))].map(code => {
              const entry = timetable.find(t => t.subject_code === code);
              return (
                <div className="legend-item" key={code}>
                  <div
                    className="legend-color"
                    style={{ background: getSubjectColor(code) }}
                  />
                  <span className="legend-code">{code}</span>
                  <span className="legend-name">{entry?.subject_name}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
