# Generated by Django 6.0.5 on 2026-05-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=20, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("building", models.CharField(default="Main Building", max_length=100)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture Hall"),
                            ("lab", "Laboratory"),
                            ("seminar", "Seminar Room"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["building", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("credits", models.PositiveIntegerField(default=3)),
                (
                    "required_capacity",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minimum room capacity needed for this subject",
                    ),
                ),
                (
                    "sessions_per_week",
                    models.PositiveIntegerField(
                        default=3, help_text="Number of sessions per week"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="accounts.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "time_slots",
                "ordering": ["day", "start_time"],
                "unique_together": {("day", "start_time", "end_time")},
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="scheduler.room",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="scheduler.subject",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="scheduler.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_entries",
                "ordering": ["time_slot__day", "time_slot__start_time"],
                "unique_together": {("room", "time_slot")},
            },
        ),
    ]
