# Generated by Django 4.2.30 on 2026-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="equipment",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of equipment like ["Projector", "Whiteboard"]',
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("lecture", "Lecture"),
                    ("lab", "Laboratory"),
                    ("seminar", "Seminar"),
                ],
                default="lecture",
                max_length=20,
            ),
        ),
    ]
