# Generated by Django 4.2.30 on 2026-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_room_equipment_subject_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="If true, the CSP solver will not modify this entry.",
            ),
        ),
    ]
