# Generated by Django 4.2.30 on 2026-09-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_timetableentry_is_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(default="08:00")),
                ("end_time", models.TimeField(default="19:00")),
                (
                    "default_breaks",
                    models.JSONField(
                        default=list, help_text='List of break times like ["13:00"]'
                    ),
                ),
            ],
            options={
                "db_table": "institution_settings",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="color_code",
            field=models.CharField(
                default="#1e293b",
                help_text="Hex color code for timetable display",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="event_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="event_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="event_type",
            field=models.CharField(
                blank=True, default="class", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="scheduler.subject",
            ),
        ),
    ]
