# Generated by Django 4.2.30 on 2026-09-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_timetableversion_notification_absencereport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencereport",
            name="timetable_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="absences",
                to="scheduler.timetableentry",
            ),
        ),
    ]
