# Generated by Django 4.2.30 on 2026-09-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_faculty_faculty_avail_gin_idx_and_more"),
        ("scheduler", "0006_absencereport_timetable_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_slots",
                        to="scheduler.timeslot",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to="accounts.faculty",
                    ),
                ),
                (
                    "target_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_targets",
                        to="scheduler.timetableentry",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_swap_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
