# Generated by Django 4.2.30 on 2026-09-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_faculty_faculty_avail_gin_idx_and_more"),
        ("scheduler", "0007_timetableswaprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_entries",
                to="accounts.faculty",
            ),
        ),
    ]
