# Generated by Django 4.2.30 on 2026-09-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0008_timetableentry_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackoutDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("reason", models.CharField(max_length=200)),
                ("is_global", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "blackout_dates",
                "ordering": ["date"],
            },
        ),
    ]
