# Generated by Django 4.2.30 on 2026-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_blackoutdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Override global start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="Override global end time", null=True
                    ),
                ),
                (
                    "default_breaks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of break times like ["13:00"]',
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="is_elective",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a shared elective across departments",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Departments that can use this room",
                related_name="rooms",
                to="scheduler.department",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Departments this subject belongs to",
                related_name="subjects",
                to="scheduler.department",
            ),
        ),
    ]
