# Generated by Django 4.2.30 on 2026-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0010_department_subject_is_elective_room_departments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "resources",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Amenities present in this room",
                related_name="rooms",
                to="scheduler.amenity",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Amenities required by this subject",
                related_name="required_by_subjects",
                to="scheduler.amenity",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Movable resources (from pools) required by this subject",
                related_name="required_by_subjects",
                to="scheduler.resource",
            ),
        ),
    ]
