# Generated by Django 4.2.30 on 2026-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_student_is_ta_student_ta_max_hours_per_week_and_more"),
        (
            "scheduler",
            "0011_amenity_resource_room_amenities_subject_amenities_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="required_tas",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of TAs required for this class"
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="teaching_assistants",
            field=models.ManyToManyField(
                blank=True, related_name="ta_assignments", to="accounts.student"
            ),
        ),
    ]
