# Generated by Django 4.2.30 on 2026-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="availability",
            field=models.JSONField(
                blank=True,
                help_text="Per-day time slot availability preferences",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="max_hours_per_week",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
