# Generated by Django 4.2.30 on 2026-09-23 17:59

from django.db import migrations
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_faculty_availability_faculty_max_hours_per_week"),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name="student",
            name="face_encoding",
        ),
        migrations.AddField(
            model_name="student",
            name="face_encoding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=128,
                help_text="128-dimensional face encoding vector",
                null=True,
            ),
        ),
    ]
