# Generated by Django 4.2.30 on 2026-09-23 18:20

import django.contrib.postgres.indexes
from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_student_face_encoding"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="faculty",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["availability"], name="faculty_avail_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["face_encoding"],
                m=16,
                name="student_face_hnsw_idx",
                opclasses=["vector_l2_ops"],
            ),
        ),
    ]
