# Generated by Django 4.2.30 on 2026-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_faculty_faculty_avail_gin_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="accessibility_needs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of needs like ["Wheelchair Access"]',
            ),
        ),
    ]
