# Generated by Django 4.2.30 on 2026-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0011_amenity_resource_room_amenities_subject_amenities_and_more",
        ),
        ("accounts", "0005_student_accessibility_needs"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_ta",
            field=models.BooleanField(
                default=False,
                help_text="Whether this student is also a Teaching Assistant",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ta_max_hours_per_week",
            field=models.PositiveIntegerField(
                default=10, help_text="Maximum hours per week the student can TA"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ta_qualified_subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects this TA is qualified to teach",
                related_name="qualified_tas",
                to="scheduler.subject",
            ),
        ),
    ]
