# Generated by Django 4.2.30 on 2026-10-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0012_subject_required_tas_and_more"),
        ("accounts", "0006_student_is_ta_student_ta_max_hours_per_week_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "academic_groups",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="faculty",
            name="department_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculty_members",
                to="scheduler.department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="department_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="scheduler.department",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="faculty_members", to="accounts.academicgroup"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="accounts.academicgroup"
            ),
        ),
    ]
