# Generated by Django 4.2.30 on 2026-10-03 20:46

from django.db import migrations


def migrate_departments(apps, schema_editor):
    Student = apps.get_model('accounts', 'Student')
    Faculty = apps.get_model('accounts', 'Faculty')
    Department = apps.get_model('scheduler', 'Department')

    dept_cache = {}

    def get_or_create_dept(dept_name):
        if not dept_name:
            return None
        if dept_name not in dept_cache:
            dept, created = Department.objects.get_or_create(name=dept_name)
            dept_cache[dept_name] = dept
        return dept_cache[dept_name]

    for student in Student.objects.all():
        if student.department:
            student.department_fk = get_or_create_dept(student.department)
            student.save(update_fields=['department_fk'])
            
    for faculty in Faculty.objects.all():
        if faculty.department:
            faculty.department_fk = get_or_create_dept(faculty.department)
            faculty.save(update_fields=['department_fk'])

def reverse_migrate_departments(apps, schema_editor):
    Student = apps.get_model('accounts', 'Student')
    Faculty = apps.get_model('accounts', 'Faculty')
    
    for student in Student.objects.all():
        if student.department_fk:
            student.department = student.department_fk.name
            student.save(update_fields=['department'])
            
    for faculty in Faculty.objects.all():
        if faculty.department_fk:
            faculty.department = faculty.department_fk.name
            faculty.save(update_fields=['department'])

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_academicgroup_faculty_department_fk_and_more"),
        ("scheduler", "0010_department_subject_is_elective_room_departments_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_departments, reverse_migrate_departments),
    ]
