# Generated by Django 4.2.30 on 2026-10-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0012_subject_required_tas_and_more"),
        ("accounts", "0008_migrate_department_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="department",
        ),
        migrations.RemoveField(
            model_name="student",
            name="department",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="department_fk",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="department_fk",
            new_name="department",
        ),
    ]
