# Generated by Django 4.2.30 on 2026-10-04 15:20

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_faculty_department_fk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_encoding",
                    pgvector.django.vector.VectorField(
                        dimensions=128, help_text="128-dimensional face encoding vector"
                    ),
                ),
                ("image", models.ImageField(upload_to="face_samples/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_samples",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "face_samples",
                "ordering": ["-created_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["face_encoding"],
                        m=16,
                        name="facesample_hnsw_idx",
                        opclasses=["vector_l2_ops"],
                    )
                ],
            },
        ),
    ]
