# Generated by Django 4.2.30 on 2026-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_facesample"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="cgpa_semesters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="CGPA per semester, e.g. {'1': 8.5, '2': 9.0}",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="marks_10th",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage or CGPA in 10th grade",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="marks_12th",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage or CGPA in 12th grade",
                max_digits=5,
                null=True,
            ),
        ),
    ]
